### ISSUE TITLE
Upgrade of depdencies

### ISSUE THREAD

**Issue by PrzemyslawKlys** [baltermia/barcodereader-imagesharp#4]
Have you considered updating dependencies to a higher version?

![image](https://user-images.githubusercontent.com/15063294/175518958-63ccb35c-9ed5-4def-b4be-7b71d0d2269e.png)

**Comment by baltermia** [comment]
Yeah, I was thinking of upgrading it to work with ImageSharp V2 when I opened it recently in VS, but I don't really have time to work too much on personal projects atm because of school exams... I will definitely release a V2 version of this project when I find time to do so. I will link the branch to this issue. 
If you want to do that you can of course upgrade the dependencies and send me a pull request (though I don't know if the code will work the same as before because we need the [ZXing.Net.Bindings.ImageSharp.V2](https://www.nuget.org/packages/ZXing.Net.Bindings.ImageSharp.V2/) library (note the v2)). So maybe it's as easy as just upgrading the nuget packages in the project files or some additional changes would be necessary.

**Comment by PrzemyslawKlys** [comment]
I did upgrade it, but then everything went to hell ;) I'll try the V2 and see.

**Comment by baltermia** [comment]
Same happened to me haha so I didn't bother spending more time with it. I created the upgrade-to-imagesharp-v2 branch you may commit your code there so we can work on it together perhaps :)

**Comment by baltermia** [comment]
So I found some time this evening. I was able to upgrade all the packages. 

I made some major changes to the BarcodeReader class, it is now generic to provide a more direct use.

The nuget package should be online :)
